# permissions for end users to view connects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: connect-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: team-operator
    app.kubernetes.io/part-of: team-operator
    app.kubernetes.io/managed-by: kustomize
  name: connect-viewer-role
rules:
- apiGroups:
  - core.posit.team
  resources:
  - connects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.posit.team
  resources:
  - connects/status
  verbs:
  - get
