apiVersion: core.posit.team/v1beta1
kind: Workbench
metadata:
  labels:
    app.kubernetes.io/name: workbench
    app.kubernetes.io/instance: workbench-sample
    app.kubernetes.io/part-of: team-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: team-operator
  name: workbench-sample
spec: {}
