apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## Append samples you want in your CSV to this file as resources ##
resources:
- posit.co_v1beta1_site.yaml
- posit.co_v1beta1_postgresdatabase.yaml
- posit.co_v1beta1_connect.yaml
- posit.co_v1beta1_workbench.yaml
- posit.co_v1beta1_packagemanager.yaml
- posit.co_v1beta1_chronicle.yaml
